Update vue-resource
* fixing TypeError: r.call is not a function(…)

* fixing TypeError: Cannot read property 'handleResponseData' of undefined(…)

* updating to latest dist files

* set minimum version of vue-resource